version: 2
registries:
  tradeshift-gcr:
    type: docker-registry
    url: eu.gcr.io
    username: _json_key
    password: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY_NOBASE64 }}
updates:
  - package-ecosystem: docker
    directory: /kubeval
    registries:
      - tradeshift-gcr
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /update
    registries:
      - tradeshift-gcr
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /validate
    registries:
      - tradeshift-gcr
    schedule:
      interval: daily
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
